### ISSUE TITLE
Update Bootstrap to 4.x.x

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#102]
## Migration guides
- https://getbootstrap.com/docs/4.0/migration/
- https://medium.com/@lukaszholeczek/migration-from-bootstrap-3-to-bootstrap-4-4ec63a1dd8b1
- https://designmodo.com/migrate-bootstrap-4/

If you simply replace Bootstrap 3.3.7 with 4.1.3 it looks bad.

**Comment by mpahl** [comment]
Converter doesn't work on templates. It would need some work updating all templates manually.
(Converter: http://upgrade-bootstrap.bootply.com/)

**Comment by hansendx** [comment]
I've created a Branch with the django tags removed. maybe this will make it easier to update.
https://github.com/ddionrails/ddionrails/tree/refactor/102-update-bootstrap-to-4

**Comment by hansendx** [comment]
Resolved in by 579fb9f11321d6ebc7eca4265e17323e861b9036  in #743
