### ISSUE TITLE
Use attachments also for publications

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#110]
Publications contain one URL - if we need multiple URLs (if DOIs, URNs, additional landing pages etc. are available) we could use the attachments feature, which provides additionally display labels for those links. Should be synchronized with the source of publications.csv.

**Comment by afuetterer** [comment]
@kwenzig: What does this mean?

> Should be synchronized with the source of publications.csv

I am not a fan of the way the `Attachment` is implemented. But if you just want to "add another arm to the octopus" we can surely do so. Meaning: The Attachment already has foreign keys to:
- "context_study" (I don't know what this is)
- study
- dataset
- variable
- instrument
- question

see: https://github.com/ddionrails/ddionrails/blob/docker_setup/ddionrails/publications/models.py#L76

We just add and it's done.
```python
publication = models.ForeignKey(
    Publication,
    blank=True,
    null=True,
    related_name="attachments",
    on_delete=models.CASCADE,
)
```
