### ISSUE TITLE
variables: description wird doppelt angezeigt

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#1122]
Bei der Variable https://paneldata.org/soep-core/data/pgen/pgpsbil wird die description doppelt angezeigt. Die Zulieferung der Metadaten https://github.com/paneldata/soep-core/blob/master/metadata/variables.csv war in der Hinsicht korrekt.

**Comment by hansendx** [comment]
Fixed in 64e179704501c7e762befb0bcc95ae8bc982bc24
