### ISSUE TITLE
search field missing

### ISSUE THREAD

**Issue by sabinekatzdobler** [ddionrails/ddionrails#1449]
Good day, 

as I attended paneldata.org regarding SOEP-data I missed the "search field", where I can type in keywords for finding e.g. variable codes. When will the "search field" on paneldata.org be provided again? At the moment it is very hard to search efficiently. 

Kind regards, 

Sabine

**Comment by sabinekatzdobler** [comment]
👍

**Comment by hansendx** [comment]
Absence of the search field was a temporary problem on the paneldata.org server and has been fixed now.
