### ISSUE TITLE
Variable salivaev: Internal Server Error (500)

### ISSUE THREAD

**Issue by jgoebel** [ddionrails/ddionrails#1503]
### Subject of the issue

Internal Server Error (500)

### Expected behaviour

documentation of variable salivaev in study soep-is

### Actual behaviour

Server reports internal server error (500)

### Steps to reproduce

See:
https://paneldata.org/soep-is/data/inno/salivaev

**Comment by hansendx** [comment]
There seemed to have been inconsistencies for soep-is in the Database. A reimported fixed the server issues.
