### ISSUE TITLE
German and English Value Labels for pgmode in pgen do not match

### ISSUE THREAD

**Issue by ingoseifert** [ddionrails/ddionrails#1606]
### Subject of the issue
For value `120` and `131` in `pgmode`, the corresponding value labels in English and German do not match. 

### Expected behaviour
As suggested by the code for the figure in the companion on different modes in SOEP (http://companion.soep.de/_downloads/ca9e9f7826c8d994d81aa8235fbd2b13/Interview_Modes.txt), 
- 131 means "**with** interviewer", hence the German translation should be "Selbstausfuellung **m. I.**"
-  and 120 means "**without** interviewer", hence the German translation should be "Selbstausfuellung **o. I.**".

### Actual behaviour
See https://paneldata.org/soep-core/data/pgen/pgmode:
[120] Written Ques. **Interviewer** [120] Selbstausfuellung **o. I.**
[131] Written Ques. **No Interviewer** [131] Selbstausfuellung **m. I.**

### Steps to reproduce
See above.

**Comment by kwenzig** [comment]
Danke. Das Issue wird im SOEP-intenen Issuetracker unter https://git.soep.de/soep-generierungen/Dokumentation/-/issues/411 weiterbearbeitet und hier geschlossen. (Dieser Tracker ist primär für die Software von paneldata.org gedacht.)
