### ISSUE TITLE
Variable Search Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Lisa2212** [ddionrails/ddionrails#2146]
1. Beim Variable Search kann man nur durch Scrollen zum Beispiel unter "Period" das Jahr suchen, für das man die Variablen angezeigt bekommen möchte. Praktisch wäre es, wenn man neben dem Begriff "Period" das entsprechende Jahr eintippen kann. Dann müsste man nicht mehr scrollen, wobei man zurzeit beim Scrollen die Jahre nicht übersichtlich angezeigt bekommt, d.h. nicht zeitlich auf- oder absteigend.
2. Beispielsweise zu der Variable bdp/f13p131c1. Ich fände es gut, wenn es eine kurze Erläuterung auf der Website (z.B. unter "help") gibt, wofür die jeweiligen Zahlen und Buchstaben stehen. Das ist mir bei bdp bewusst, jedoch zu c1 ist es mir gerade unklar.
3. Ich fände es hilfreich, wenn auf der Seite zu einer Variable (z.B. zu bdp/f13p131c1) dann die PDF-Datei verlinkt ist mit dem entsprechenden Fragebogen aus dem entsprechenden Jahr in deutsch und englisch.

Vielen Dank im Voraus und freundliche Grüße

**Comment by hansendx** [comment]
Vielen Dank für das Feedback.

Bei 1. würde ich zustimmen und das Suchfeld und die Sortierung (wäre dann alphabetisch, weil Wellen nicht unbedingt immer Jahreszahlen sind aber das Ergebnis wäre ungefähr gleich) beim nächsten Planungstreffen ansprechen und dann wahrscheinlich umsetzten.

Zu 2. und 3.: Das Portal beinhaltet bereits die Funktionen, die für soetwas benötigt würden.
2. zum Beispiel kann als Teil der Description eingebunden werden  und 3. als Attachement.
Dafür müsste diese Information allerdings in den Metadaten vorhanden sein, liegt also außerhalb meines Arbeitsbereichs.
Ich kann das aber weiterleiten an die SOEP-Core Datengenerierung.

**Comment by kwenzig** [comment]
Zu den Punkten 2 und 3:
Die Benennungsschemata für Variablen haben sich im SOEP über die Zeit geändert. Schon immer gab es auch in unterschiedlichen Bereichen des Datenangebots unterschiedliche Benennungslogiken. Insgesamt wird es wohl bei der Komplexität des SOEP unmöglich sein, aus dem Variablennamen die Informationen zu erhalten, die benötigt sind, um die Variable korrekt zu verstehen. (Grundsätzlich geben die ersten 1-2 Buchstaben einen Hinweis auf die Welle, der folgende Buchstabe einen Hinweis auf den Typ des Erhebungsinstruments, die folgenden Zahlen einen Hinweis auf die Fragenummer und weitere Informationen einen Hinweis auf das Item. In jüngerer Zeit gibt es ein q-Suffix, dass eine genauere Beziehung zum Fragebogen herstellt.)
Unser Ziel, dem wir uns in jüngeren Wellen bereits sehr gut anähern, ist die Bereitstellung der entsprechenden Informationen auf paneldata.org. Schauen wir uns die entsprechende Seite auf paneldata.org an: https://paneldata.org/soep-core/data/bdp/f13p131c1 (Und die Variable ist ein gutes Beispiel, weil durchaus verschiedene Informationsquellen – mit unterschiedlichen Stärken und Schwächen – benötigt und verfügbar sind, um den Inhalt tatsächlich zu verstehen.)

1. Leider ist mit dieser Variable noch keine Frage erfasst. Sie würde in der rechten Spalte erscheinen.
2. Aber es gibt neuere "ähnliche" Variablen, was in der Tabelle "Related Variables" ersichtlich ist, etwa diese: https://paneldata.org/soep-core/data/bgp/bgp151d01
3. Hier findet sich auch eine Frageformulierung in der rechten Spalte, es sind tatsächlich mehrere, weil Informationen aus mehreren Erhebungsinsturmenten in bgp151d01 eingegangen sind, z.B. https://paneldata.org/soep-core/inst/soep-core-2016-pe/151
4. Hier zeigt sich, dass die Frage ein recht komplexes Design hat und viele Variablen erzeugt, weil unterschiedliche Beziehungen zu vielen Personen abgefragt werden. Aber mit Blick auf das Variablenlabel (Mit Person 1 im belastenden Streit) enthät die Variable die Kennziffer einer Person, mit der man sich im Streit befindet.
5. Mit internem Wissen ist auch klar, dass die zu f13p131c1 gehörende Frage aus einem Fragebogen der FiD-Studie stammt, was noch nicht angezeigt wird. Jedoch führt auch eine Google-Suche (https://www.google.com/search?q=f13p131c1) zu einem entsprechenden PDF, in dem die Variable enthalten ist: https://www.diw.de/documents/publikationen/73/diw_01.c.571223.de/diw_ssp0405.pdf
6. Die Feldversion dieses PAPI-Fragebogen findet sich in diesem Suchportal: https://www.diw.de/de/diw_01.c.789785.de/dokumentationen_soep-core___soep_survey_papers.html. Wenn dort nach "Erhebungsinstrumente", "2013" und "Person" seletiert, kann man bei diesem Dokument landen: https://www.diw.de/de/diw_01.c.785598.de/s_8617.html und findet dort in Frage 131 die Printversion der Frage und kann damit die Variable f13p131c1 besser verstehen.

Sicher ist das keine zufriedenstellende Lösung, aber am Beispiel der Variable https://paneldata.org/soep-core/data/bgp/bgp151d01 ist unser angestrebter "Endausbau" zu sehen: In der rechten Spalte unter Questions ist die Frage dreimal verlinkt. Eine ist z.B. https://paneldata.org/soep-core/inst/soep-core-2016-pe/151. Hier kann man in vielen Fällen bereits den Variableninhalt verstehen. Wenn man hier in der rechten Spalte auf den Fragebogen ("Individual (PAPI) 2016") klickt, landet man beim Fragebogen https://paneldata.org/soep-core/inst/soep-core-2016-pe, für den auch PDFs vorhanden sind, die die Frage 151 erklären: Die Feldversion enthält die gedruckte Fassung (https://www.diw.de/documents/publikationen/73/diw_01.c.571045.de/diw_ssp0345.pdf) und die Version mit Variablen (https://www.diw.de/documents/publikationen/73/diw_01.c.618898.de/diw_ssp0637.pdf) enthält eine Ansicht, in der die Variablen etwas besser zugeordnet sind, hier zu Unterfrage d.

**Comment by hansendx** [comment]
Punkt 1 ist jetzt in der neusten Version der Plattform umgesetzt und 2 bis 3 sind in @kwenzig  Kommentar erläutert.

**Comment by Lisa2212** [comment]
Vielen Dank!
