### ISSUE TITLE
500 Error when trying to open pages for variables lm1026, lm1027, lm1028 

### ISSUE THREAD

**Issue by mgauer** [ddionrails/ddionrails#2373]
### Subject of the issue

Describe your issue here.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

Tell us how to reproduce this issue.

**Comment by hansendx** [comment]
Thank you for the error report.
Problem was caused by the related concepts because their name included non alphanumeric characters.
I changed the routing for copncepts to fix the problem.
