### ISSUE TITLE
Update welcome message on home page

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#301]
In the develop-Branch we currently have:
"Update November 2018: Bugfixes and new features for baskets and script generator, such as an improved layout, CSV export and new options to edit."

What do we display there now?

**Comment by kwenzig** [comment]
> Update March 2019: A completly redesigned topic list enables interest-driven access to variables and questions. Related questions show how a question has evolved in time. New tables for related variables, input and output variables show relations between variables.

**Comment by afuetterer** [comment]
Should both message appear?

"
Update March 2019: A completly redesigned topic list enables interest-driven access to variables and questions. Related questions show how a question has evolved in time. New tables for related variables, input and output variables show relations between variables.

Update November 2018: Bugfixes and new features for baskets and script generator, such as an improved layout, CSV export and new options to edit.
"
