### ISSUE TITLE
Decide what to do with study_publication_list view

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#354]
### Subject of the issue
The `study_publication_list` has a commented line:
https://github.com/ddionrails/ddionrails/blob/971138ae8cb5df2276f29089f132e34a3cbf3830/ddionrails/publications/views.py#L44
If you remove the comment, then publications will appear in a table in the template.
Is this behaviour desired?
If so, let me remove the comment sign and and refactor this view in to a proper `ListView`.
If not remove the comment.

**Comment by afuetterer** [comment]
@kwenzig: What is the purpose of https://paneldata.org/soep-core/publ/?

- [ ] 1. the page should display a search bar (with no results when opened) like https://paneldata.org/search/
- [ ] 2. the page should display a data-table (like the ones for datasets and variables) for the study like https://paneldata.org/soep-core#datasets
- [ ] 3. both: above a search bar for elasticsearch and below a datatable

At the moment the page does 1. but the commented line would do 3.

Depending on your answer I will address this issue.

**Comment by jgoebel** [comment]
What will be the behaviour of option 3? What publications will be listed? By alphabetic order of author name, or the most recent?

**Comment by afuetterer** [comment]
I could provide screenshots of all three options.
The data-table would contain all publications of the corresponding study:
```python
study.publications.all()
```
The ordering is up to us. I am not sure which order the default is, but I guess time of import, as it is not specified in the query.

@jgoebel: Do you prefer a "publication list" or a "publication search"? The mixture of both looks odd in my opinion. Do you want a demo of the three options?

**Comment by jgoebel** [comment]
I agree that a mixture may look odd.  Another possibility would be that the page should start with alle publications listed, like the results page when searching for "*".
If you could provide a demo this would be helpful.

**Comment by afuetterer** [comment]
In the progress of redesigning the search UI this issue got solved on the side.
The way to display publications and enable a search over them looks like this:
https://ddionrails.soep.de/search/publications?Study=%5B%22SOEP-Core%22%5D

**Comment by afuetterer** [comment]
Closing this.
