### ISSUE TITLE
Create docker-compose.yml setup

### ISSUE THREAD

**Issue by hansendx** [ddionrails/ddionrails#395]
- [x] Add docker compose
- [x] Add Dockerfile for services to set them up
    - [x] Django

**Comment by afuetterer** [comment]
"Services" running now:
- apache, mod_wsgi, django, sqlite
- redis
- rqworker
- elasticsearch

Services to set up:
- nginx
- gunicorn / uwsgi
- postgres
- elasticsearch
- redis
- (rqworker ?)
