### ISSUE TITLE
Bring Docker setup to develop Branch

### ISSUE THREAD

**Issue by hansendx** [ddionrails/ddionrails#425]
### Docker Setup is almost done and needs to be brought to develop branch
Needs to be tested on staging:
- [x] Does it run as expected?
- [x] Do imports work?
- [x] Does Data persist?

**Comment by afuetterer** [comment]
- [ ] tests run through
- [ ] importing to database works
- [ ] indexing into search engine works
- [ ] rqworker enables imports with queue
- [ ] search ui works
