### ISSUE TITLE
Topics: load error next to concepts

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#428]
### Subject of the issue
Go to any topic within the topic list. When a concept is selected, a Load Error appears.

![grafik](https://user-images.githubusercontent.com/6614820/57453649-3bae7e00-7267-11e9-959b-fe8e79c1e3a9.png)

### Expected behaviour
Display of questions and ariables like for topics. (There it works.)

**Comment by hansendx** [comment]
We found the problem.
It is related to #574 and i will further address it there.
A fix on the live system will take some Time.

**Comment by hansendx** [comment]
@kwenzig the problem is fixed now. #574
