### ISSUE TITLE
script generator: update to v35

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#429]
### Subject of the issue
If I add variables from file bhp or any other new (raw) files new in v34, they will not be processed by the generator.

**Comment by afuetterer** [comment]
Responsible code: `SoepMixin`.
see: https://github.com/ddionrails/ddionrails/blob/develop/workspace/scripts.py#L51

**Comment by afuetterer** [comment]
@kwenzig The variable itself is not important, right? The bug is encountered when using any variable from `bhp`?

**Comment by kwenzig** [comment]
Yes. I expect any variable from any file, which is new in v34 to be not processed.
As far as I understand the code, there are some guesses, like: this file is a p file, this file is a h file. I would suggest to switch from these guesses to metadata and offer to prepare them.

**Comment by afuetterer** [comment]
Yes!
This "p" and "h" is exactly what the "analysis unit" relation should be used for. Do you have datasets that are neither "h" or "p"? See the related issue #132 where some datasets are falsely classified.

Also there is some "magic" with the soep letters which should be addressed via period relations.

**Comment by hansendx** [comment]
Should be addressed in #1009
