### ISSUE TITLE
Add image link to question entity

### ISSUE THREAD

**Issue by hansendx** [ddionrails/ddionrails#502]
### Subject of the issue
A question should be diplayed with images showing the actual question, as it was seen by paritcipants in the study.

Prerequisites:
- [x] A data model for images needs to exist. 
- [x] There needs to be a reference between the images and the instruments.Question model.
- [x] The image needs to be displayed through templates/question/question_detail.html

**Comment by afuetterer** [comment]
Please wait for #507 to complete.

**Comment by afuetterer** [comment]
Go ahead.
