### ISSUE TITLE
ddionrails.base.mixins uses eval for questionable purposes

### ISSUE THREAD

**Issue by hansendx** [ddionrails/ddionrails#555]
### Subject of the issue

eval executes arbitrary python code and is used by the modelMixin to get attributes of objects:

https://github.com/ddionrails/ddionrails/blob/0a9b1d2d490ad7fc9ce90d5e6f68bfaf06c06bf3/ddionrails/base/mixins.py#L94-L106

https://github.com/ddionrails/ddionrails/blob/0a9b1d2d490ad7fc9ce90d5e6f68bfaf06c06bf3/ddionrails/base/mixins.py#L134-L143

https://github.com/ddionrails/ddionrails/blob/0a9b1d2d490ad7fc9ce90d5e6f68bfaf06c06bf3/ddionrails/base/mixins.py#L134-L155

Dedicated functionality should be used to do this instead, i.e. getattr().
This might have to be done recursively since the functions seem to have been used to get attributes over an arbitrary number of relations, e.g. object.objectAttribute.attribute or object.attribute.

**Comment by afuetterer** [comment]
@hansendx Did you find any occurences where this is used?
I did a quick search for ".get_attribute" and found nothing.

Just remove it?
