### ISSUE TITLE
Syntaxgenerator: Optimierungsbedarf für Stata-Syntax

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#56]
* der verwendete ```merge```-Befehl ist veraltet, es muss die Art der Relation spezifiziert werden (```1:1```, ```m:1``` etc.).
* Dann können auch die vielen Zeilen mit ```sort``` wegfallen.
* Außerdem sollten statt ```drop if _merge == 2``` und ```drop _merge``` die Optionen ```keep(master, match)``` und  ```nogen``` verwendet werden.
* alle ```use```-Komandos (auch das erste!) sollten die Option ```clear``` verwenden. Die entsprechende Zeile mit ```clear``` kann dann entfallen.

**Comment by afuetterer** [comment]
Erledigt im Rahmen des externen Auftrags.
