### ISSUE TITLE
Remove password_reset_done.html?

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#563]
### Subject of the issue
The templates "login.html" and "password_reset_done.html" have the same contents.

If we overwrite "password_reset_done.html" the system will show this template instead of Django's default, which says:

> ### Password reset sent
> We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
> 
> If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.

@hansendx 
Do we want to:
- ~redirect to login instead?~
- [x] provide a custom password_reset_done?
- ~use Django's default password_reset_done?~

**Comment by hansendx** [comment]
redirect to login, with "yout password has been reset etc." message?

**Comment by hansendx** [comment]
Maybe we should change the password_reset_done.html to dispay a success message and a button, that links back to the login page.

**Comment by afuetterer** [comment]
Be my guest. :smile:
If you do not use a custom page, it would look liket this:
https://wsvincent.com/assets/images/django-user-authentication-tutorial/django-password-reset-done.png

**Comment by hansendx** [comment]
The template actually needs to be called password_reset_complete.html for django to use it.
