### ISSUE TITLE
Accept umlauts when searching for variables

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#60]
Die zwei Suchanfragen unterscheiden sich nur durch den in einem Fall ausgeschriebenen Umlaut:

https://data.soep.de/search/?q=%2Bnamespace%3A%27soep-long%27+rauchen+gegenwaertig

https://data.soep.de/search/?q=%2Bnamespace%3A%27soep-long%27+rauchen+gegenw%C3%A4rtig

Nur wenn man den Umlaut umschreibt, wird die sehr einschlägige Variable <https://paneldata.org/soep-core/data/pl/ple0081> gefunden. Das concept erscheint gar nicht.

**Comment by afuetterer** [comment]
Search for "rauchen gegenwaertig" or "rauchen gegenwärtig" and study "soep-core" should yield variable "ple0081".

**Comment by afuetterer** [comment]
- [ ] add test case
