### ISSUE TITLE
Search in field "label_de" for concepts

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#61]
Die Suche https://data.soep.de/search/?q=%2Bnamespace%3A%27soep-core%27+zufriedenheit+gesundheit sollte wenigstens in Ansätzen auch zum concept https://data.soep.de/concept/pzuf01 und damit verbundenen Variablen, z.B. https://data.soep.de/soep-core/data/ap/ap0301 führen.

**Comment by afuetterer** [comment]
Search for "zufriedenheit gesundheit" and study "soep-core" should yield concept "pzuf01" and variable "ap0301".

**Comment by afuetterer** [comment]
- [ ] add test case

**Comment by afuetterer** [comment]
- https://ddionrails.soep.de/search/variables?Study=%5B"SOEP-Core"%5D&Search="Zufriedenheit+Gesundheit"&Period=%5B"1984"%5D
- https://ddionrails.soep.de/search/concepts?Search=%22zufriedenheit+gesundheit%22&Study=%5B%22SOEP-Core%22%5D
