### ISSUE TITLE
Table html templates are redundant. 

### ISSUE THREAD

**Issue by hansendx** [ddionrails/ddionrails#659]
There are several table templates for displaying data in tables.
At least

- templates/data/translation_table.html
- templates/data/dataset_table.html
- templates/data/variable_table.html

could be condensed into one template.
There might be more.

**Comment by afuetterer** [comment]
There might be more, indeed.
see #563

**Comment by hansendx** [comment]
Related to #967.
There has to be an efficient way to get from python data structures to HTML tables.
