### ISSUE TITLE
Add search documents

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#680]
relates to #597

# Search documents
- [x] Concept
- [x] Topic
- [x] Variable
- [x] Question
- [x] Publication

### Concept
Fields:
- [x] name
- [x] label
- [x] label_de
- [x] description
- [x] description_de

Facets:
- [x] study.title() (through Topic, Variable, Question, see https://github.com/ddionrails/ddionrails/issues/680#issuecomment-510486977)

### Topic
Fields:
- [x] name
- [x] label
- [x] label_de
- [x] description
- [x] description_de

Facets:
- [x] study.title()

### Variable
Fields:
- [x] name
- [x] label
- [x] label_de
- [x] description
- [x] description_de
- [x] description_long
- [x] categories (labels, labels_de)
- [x] dataset_name
- [x] concepts (name, label, label_de)

Facets:
- [x] study.title()
- [x] analysis unit.title()
- [x] conceptual dataset.title()
- [x] period.title()

### Question
Fields:
- [x] label
- [x] label_de
- [x] description
- [x] description_de
- [x] text
- [x] text_de
- [x] answers: label/label_de

Facets:
- [x] study.title()
- [x] analysis unit.title()
- [x] period.title()

### Publication
Fields:
- [x] abstract
- [x] author
- [x] cite
- [x] doi
- [x] name
- [x] title
- [x] url

Facets:
- [x] study.title()
- [x] sub_type
- [x] year

**Comment by afuetterer** [comment]
When is a concept related to a study?
- [ ] study - topic - concept
- [ ] study - dataset - variable -concept
- [ ] study - instrument -question -concept

**Comment by afuetterer** [comment]
@kwenzig @hansendx  : Do you really want to index "name" for publications, which is mostly "1", "2", etc.
Also do you really want to index urls?

**Comment by kwenzig** [comment]
> @kwenzig @hansendx : Do you really want to index "name" for publications, which is mostly "1", "2", etc.
> Also do you really want to index urls?
Yes,
