### ISSUE TITLE
Create elasticsearch proxy with nginx?

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#727]
### Subject of the issue

The search frontend cannot access http://elasticsearch:9200. A selenium test inside the ddi_net docker network can access it alright.

Do we need a proxy for that?

Should django handle something like this?
https://github.com/ddionrails/ddionrails/blob/191e0f0fa95c81e58783a1b1317e0c705a19e51a/config/views.py#L58-L64

**Comment by hansendx** [comment]
More something like
```
location /search/ {
    proxy_pass http://elasticsearch:9200
}
```
in the nginx config.
The example would however not work. resolving the hostname elasticsearch needs some extra work.
We could also bind elasticsearch to a specific IP in the docker network.

**Comment by afuetterer** [comment]
`/search/` is already used in Django's URLConf. Is that a problem?
