### ISSUE TITLE
Decision: Icons for models

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#729]
### Subject of the issue
There are inconsistent usages of icons.
Please decide which icon stands for which model:
- [x] variable
- [x] concept
- [x] topic
- [x] question
- [x] publication

**Comment by hansendx** [comment]
### Use this:
- variable: https://fontawesome.com/icons/chart-bar?style=solid


### Unsure
This might make the connection between Topics and concepts more clear?:
- [ ] concept: https://fontawesome.com/icons/cog?style=solid
- [ ] topic: https://fontawesome.com/icons/cogs?style=solid

The Question mark would be something more associated with a question, the checkbox is more in tune with the old icon:
- [ ] question: https://fontawesome.com/icons/question-circle?style=regular
- [ ] question: https://fontawesome.com/icons/check-square?style=regular

The Book icon looks somewhat heavy, the newspaper icon looks like it might not be recognized as such.
- [ ] publication: https://fontawesome.com/icons/newspaper?style=regular
- [ ] publication: https://fontawesome.com/icons/book?style=solid

**Comment by hansendx** [comment]
I had problems with the newspaper icon  https://fontawesome.com/icons/newspaper?style=regular.
It is not displayed as regular but as solid.
