### ISSUE TITLE
Display frequencies grouped by wave

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#731]
### Subject of the issue
@kkrell requested to display frequencies of variables grouped by wave.

Original issue: paneldata/twinlife#50

**Comment by kkrell** [comment]
Hallo, sorry wenn ich hier dazwischenfunke. 

Eine weitere Anfrage aus dem Issue 50 war, anzuzeigen, in welchen Wellen die Variable erhoben wurde - nicht nur die Häufigkeit nach Wellen.
Zitat: Anzeige, in welchen Wellen eine Variable erhoben wurde. Quasi eine Auflistung z.B. unter dem Häufigkeitsdiagramm der Variable: F2F1, CATI1, [F2F2], ... wenn die Variable jedes Jahr erhoben wurde, aber auch F2F1, F2F2 usw. wenn sie zwischendurch in CATI1 nicht erhoben wurde.

--> Die Info wäre vergleichbar mit der Anzeige in Knut Wenzigs Codebook, da finden wir das auch eine nützliche Information. Wir könnten sie jetzt schon bereitstellen, müssten jedoch wissen, in welchem csv an welcher Stelle das stehen müsste, damit es im System angezeigt werden kann.

**Comment by afuetterer** [comment]
Danke für das Feedback.

**Comment by kkrell** [comment]
Hallo,
könnt ihr zu diesem Punkt eine Aussage machen, ob es (in Zukunft) möglich ist? Das wäre ein recht interessanter Aspekt für uns.

Viele Grüße,
Kristina
