### ISSUE TITLE
questions.csv: Rules for filter and goto

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#78]
1. Multiple gotos in one cell should be separated by semicolons `;` That makes complex gotos like
   `1,2 @ Q2; 3 @ Q3` better parsable without using parentheses.
2. A common default for routing will be: “If there are no gotos go to next question.” Sometimes one will want to deviate from this default and a keyword `exit` would make this better recognizable, e.g. `1,2 @ Q10; exit @ Q11`.

**Comment by afuetterer** [comment]
@kwenzig: Is this issue related to the software `ddionrails` or is it better moved here https://github.com/paneldata/data-specification?
