### ISSUE TITLE
i18n: labels, descriptions

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#80]
- label should be multilingual for: variables (done), variable_categories (done), answers (done), questionnaires, questions (also if I would not recommend to use it), datasets, studies, concepts, topics, etc.
- description (or similar field which stores additional information like an abstract, generation information) should be available for: variables (used by codebook), questionnaires, datasets, studies, concepts, topics etc.

**Comment by afuetterer** [comment]
##  Label / Label de
- [ ] variable
- [ ] variable_categories
- [ ] answers
- [ ] instrument
- [ ] question
- [ ] dataset
- [ ] study
- [ ] concept
- [ ] topics

## Description
- [ ] variable
- [ ] instrument
- [ ] dataset
- [ ] study
- [ ] concept
- [ ] topic

@kwenzig: What is etc.?
