### ISSUE TITLE
Search results stats show 10.000 results only

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#815]
### Subject of the issue

If a search query yields more than 10.000 results, the number of results in the stats section still stays at:
`10000 results found in 1ms`.
This did not occur using Elasticsearch 6, I think.

**Comment by hansendx** [comment]
It would probably be more transparent if it said `more than 10000 results found in ...`.
But the exact number is probably irrelevant at this point.

**Comment by afuetterer** [comment]
Okay, I agree. Google for example says "about 1.000.000.000 result". But 60.000 is not  "about 10.000". So probably "moren than 10.000" is fine.

See  `renderResultStats` on <https://opensource.appbase.io/reactive-manual/vue/result-components/reactivelist.html#props>. Maybe you could add 
if `totalResults` == 10.000, print more than 10.000

Something like this?

**Comment by hansendx** [comment]
I looked a bit through the code and at the elasticsearch API.
The 10,000 comes definitely from elasticsearch. The real value could be obtained by setting the `scroll` value, either in the API call or somewhere as a default value. This might however be to resource expensive in the long run.
I am going to look at how we could alter the `10000 results found in x` message without changing the reactivesearch code.
