### ISSUE TITLE
Error in script generator: processing of $luecke-Files

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#961]
### Subject of the issue

If a basket contains a variable (e.g. bepluecke/bep120701) from a $luecke file, the script generator produces the fillowing line :
```
use persnr behhnr bep120701 using "${MY_PATH_IN}bepluecke.dta", clear
```

### Expected behaviour

If $hhnr is needed, it should be bfhhnr.

### Actual behaviour

The scripts wants to use a $hhnr-variable which is not existing in the dataset.

**Comment by hansendx** [comment]
#1009

**Comment by kwenzig** [comment]
Most recent behavior:
```
use persnr bep120701 using "${MY_PATH_IN}bepluecke.dta", clear
```
Missing of any $hhnr is fine because https://github.com/ddionrails/ddionrails/issues/1222
